package Eats.Unlimited.View;

import javax.swing.*;
import java.awt.*;

public class UEForm {
    private JPanel myUEPanel;
    private JButton generateButton;
    private JButton accountsButton;
    private JLabel welcomeLabel;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        myUEPanel = new JPanel();
        myUEPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(3, 3, new Insets(4, 4, 4, 4), -1, -1));
        myUEPanel.setBackground(new Color(-3287855));
        final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
        myUEPanel.add(spacer1, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 3, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, 1, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer2 = new com.intellij.uiDesigner.core.Spacer();
        myUEPanel.add(spacer2, new com.intellij.uiDesigner.core.GridConstraints(0, 2, 3, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        accountsButton = new JButton();
        accountsButton.setText("Accounts");
        myUEPanel.add(accountsButton, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        generateButton = new JButton();
        generateButton.setAutoscrolls(false);
        generateButton.setBorderPainted(true);
        generateButton.setContentAreaFilled(false);
        generateButton.setEnabled(true);
        generateButton.setFocusable(true);
        generateButton.setHideActionText(false);
        generateButton.setIcon(new ImageIcon(getClass().getResource("/Eats/Unlimited/View/gears.png")));
        generateButton.setText("");
        generateButton.setVisible(true);
        generateButton.setPreferredSize(new Dimension(30,30));
        myUEPanel.add(generateButton, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, 1, 1, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return myUEPanel;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }
}
